config/routes.rb
MyApp::Application.routes.draw do

  resources :enquiries

  get 'static_pages/home'
  get 'static_pages/products'
  get 'static_pages/contact'
  get 'static_pages/help'
  get 'static_pages/story'

  root to: 'static_pages#home'
  match '/signup',  to: 'users#new'

  match '/home',        to: 'static_pages#home'
  match '/products',    to: 'static_pages#products'
  match '/contact',     to: 'static_pages#contact'
  match '/help',        to: 'static_pages#help'
  match '/story',        to: 'static_pages#story'

  resources :stories

  resources :users
  match '/signup',      to: 'static_pages#help'

end

app/models/enquiry.rb
class Enquiry < ActiveRecord::Base
  attr_accessible :address, :comments, :email, :itemcode, :name, :phone, :pieces
end

app/controllers/enquiries_controller.rb
class EnquiriesController < ApplicationController
  # GET /enquiries
  # GET /enquiries.json
  def index
    @enquiries = Enquiry.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @enquiries }
    end
  end

  # GET /enquiries/1
  # GET /enquiries/1.json
  def show
    @enquiry = Enquiry.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @enquiry }
    end
  end

  # GET /enquiries/new
  # GET /enquiries/new.json
  def new
    @enquiry = Enquiry.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @enquiry }
    end
  end

  # GET /enquiries/1/edit
  def edit
    @enquiry = Enquiry.find(params[:id])
  end

  # POST /enquiries
  # POST /enquiries.json
  def create
    @enquiry = Enquiry.new(params[:enquiry])

    respond_to do |format|
      if @enquiry.save
        format.html { redirect_to @enquiry, notice: 'Enquiry was successfully created.' }
        format.json { render json: @enquiry, status: :created, location: @enquiry }
      else
        format.html { render action: "new" }
        format.json { render json: @enquiry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /enquiries/1
  # PUT /enquiries/1.json
  def update
    @enquiry = Enquiry.find(params[:id])

    respond_to do |format|
      if @enquiry.update_attributes(params[:enquiry])
        format.html { redirect_to @enquiry, notice: 'Enquiry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @enquiry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enquiries/1
  # DELETE /enquiries/1.json
  def destroy
    @enquiry = Enquiry.find(params[:id])
    @enquiry.destroy

    respond_to do |format|
      format.html { redirect_to enquiries_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/enquiries_helper.rb
module EnquiriesHelper
end

app/views/enquiries/_form.html.erb
<%= form_for(@enquiry) do |f| %>
  <% if @enquiry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@enquiry.errors.count, "error") %> prohibited this enquiry from being saved:</h2>

      <ul>
      <% @enquiry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.number_field :phone %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_area :address %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :itemcode %><br />
    <%= f.number_field :itemcode %>
  </div>
  <div class="field">
    <%= f.label :pieces %><br />
    <%= f.number_field :pieces %>
  </div>
  <div class="field">
    <%= f.label :comments %><br />
    <%= f.text_area :comments %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/enquiries/edit.html.erb
<h1>Editing enquiry</h1>

<%= render 'form' %>

<%= link_to 'Show', @enquiry %> |
<%= link_to 'Back', enquiries_path %>

app/views/enquiries/index.html.erb
<h1>Listing enquiries</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Phone</th>
    <th>Address</th>
    <th>Email</th>
    <th>Itemcode</th>
    <th>Pieces</th>
    <th>Comments</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @enquiries.each do |enquiry| %>
  <tr>
    <td><%= enquiry.name %></td>
    <td><%= enquiry.phone %></td>
    <td><%= enquiry.address %></td>
    <td><%= enquiry.email %></td>
    <td><%= enquiry.itemcode %></td>
    <td><%= enquiry.pieces %></td>
    <td><%= enquiry.comments %></td>
    <td><%= link_to 'Show', enquiry %></td>
    <td><%= link_to 'Edit', edit_enquiry_path(enquiry) %></td>
    <td><%= link_to 'Destroy', enquiry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Enquiry', new_enquiry_path %>

app/views/enquiries/new.html.erb
<h1>New enquiry</h1>

<%= render 'form' %>

<%= link_to 'Back', enquiries_path %>

app/views/enquiries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @enquiry.name %>
</p>

<p>
  <b>Phone:</b>
  <%= @enquiry.phone %>
</p>

<p>
  <b>Address:</b>
  <%= @enquiry.address %>
</p>

<p>
  <b>Email:</b>
  <%= @enquiry.email %>
</p>

<p>
  <b>Itemcode:</b>
  <%= @enquiry.itemcode %>
</p>

<p>
  <b>Pieces:</b>
  <%= @enquiry.pieces %>
</p>

<p>
  <b>Comments:</b>
  <%= @enquiry.comments %>
</p>


<%= link_to 'Edit', edit_enquiry_path(@enquiry) %> |
<%= link_to 'Back', enquiries_path %>