config/routes.rb
MyApp::Application.routes.draw do

  resources :enquiries

  get 'static_pages/home'
  get 'static_pages/products'
  get 'static_pages/contact'
  get 'static_pages/help'
  get 'static_pages/story'

  root to: 'static_pages#home'
  match '/signup',  to: 'users#new'

  match '/home',        to: 'static_pages#home'
  match '/products',    to: 'static_pages#products'
  match '/contact',     to: 'static_pages#contact'
  match '/help',        to: 'static_pages#help'
  match '/story',        to: 'static_pages#story'

  resources :stories

  resources :users
  match '/signup',      to: 'static_pages#help'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>

  </small>
  <nav>
    <ul>

    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "My app", '#', id: "logo" %>
      <nav>
        <ul class="nav pull-center">
          <li><%= link_to "Home",    root_path %></li>
          <li><%= link_to "How you can help",    help_path %></li>
          <li><%= link_to "Products", products_path %></li>
          <li><%= link_to "Success stories", stories_path %></li>
          <li><%= link_to "Contact Us", contact_path %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
    <%= full_title(yield(:title)) %>
  </title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
  <link type="text/css" rel="stylesheet" href="stylesheet/static_pages.css.scss"/>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
    <%= yield %>
  <%= debug(params) if Rails.env.development? %>
</div>
</body>
</html>